# Bash Aliases Configuration
# 个人常用 Bash 别名配置

# 基础命令增强
alias ll='ls -alF'
alias la='ls -A' 
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Git 相关
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline'
alias gd='git diff'
alias gb='git branch'
alias gco='git checkout'

# 系统信息
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias ps='ps aux'

# 网络相关
alias ping='ping -c 5'
alias ports='netstat -tuln'

# 开发相关
alias py='python3'
alias pip='pip3'
alias serve='python3 -m http.server'

# 自定义快捷命令
alias workspace='cd ~/personal-workspace'
alias notes='cd ~/personal-workspace/notes'
alias scripts='cd ~/personal-workspace/scripts'
